### PR TITLE
Update packet sensor value to be signed, corrected value logic in render.py

### PR DESCRIPTION
**Pull request by ghost**
Corrected sensor output and rendering.

### CODE REVIEW

**Comment by nh2** [comment]
@bschumacher @fractalcat What's the idea behind that, do we know that the value is suposed to be signed (for some processing program), or do we just want it to appear so?

**Comment by bschumacher** [comment]
It is an analog wave value. Does it break your processing application or was it just a question?

Thanks,
Bill Schumacher

**Comment by fractalcat** [comment]
The raw value is unsigned (1 LSB to 0.51 microvolts); as @bschumacher says, the observation is of a signed quantity with (digital) range `-2^13` to `2^13`. At least, I assume it is - it's not mentioned in the device docs, but I don't see how any other interpretation would make sense. Do you disagree with the interpretation of the data, or with the fact of interpreting the data rather than using the raw values?

**Comment by nh2** [comment]
No, it was just a question - given that the old unsigned behaviour had been there for so long.

Thanks for the explanation! Feel free to close.

**Comment by fractalcat** [comment]
Yeah, I'm not sure what the logic behind the original behaviour was; I never used the Python module myself so I only noticed it when @bschumacher pointed it out.

Already closed. :)

**Pull request merged**
