### PR TITLE
BREAKING CHANGE - py3 support, remove gevents, replace Crypto with cryptography

### PR DESCRIPTION
**Pull request by jonrei**
Note that this is a **breaking change**, and will break all examples and all old code that uses emokit.
Since gevent is no more, threading must be handled by the user.

New usage would be along the lines:

    import emotiv
   
    for packet in emotiv.get_packets():
          # do stuff with packet...

### CODE REVIEW

**Comment by warrenarea** [comment]
I think I read, perhaps as a comment in the code, was that part of the original 
intentions of using gevent, was that it allowed it to operate asynchronously, so
that it had the potential to connect to multiple headset devices at the same time.

So i think you have to ask, the likelihood that anyone is going to be using two
headsets in conjunction, which, unless you've done some modding to your hardware,
is going to be pretty unlikely, as you cant really fit two headsets over each other,
and even if you could, you wouldn't have any desired placement of sensors.

The only other scenario, is if you had two separate people who wanted to use the
headsets at the same time, for a single application, which is probably unlikely as well.

So I think its safe to say, we can do without gevent, and am I right to assume that does
away with greenlets as well?

ironically though, by switching to Python 3, it means we can use the improved
gevent version, which is a lot more stable and i think actually closes the greenlets properly.

When I switched from py2.7 to py3, i did not notice any improvement in performance,
although I do think the transition should be made to Py3, if all else, to fix some potential
errors in the future. 

My suggestion is, to have two folders:

Python 2.7
Python 3.3

So we keep the backwards compatibility, but we just let everyone know, that we
will be focusing on Py3 development, and the 2.7 is just for legacy applications.

To simplify execution, I also recommend putting batch files, (or makefile), where you
reference the correct Python versions executable.

**Comment by qdot** [comment]
So I'm kinda stuck between a rock and a hard place here. This library desperately needs a breaking-change version rev, as the original script has just snowballed into what we have now. It's be really nice to have a composable system of protocol and access varieties so things like gevent are quarantined, get tests in for each of the objects, documentation, etc. I've got other python projects that are far less used and far more CI'd/documented than this one now. :)

On the other hand, I'm really not sure what the usage model for this looks like anymore. are people just using the main script and reading off stdout? Or are they using it as a library too? Also, I don't want to go in, make a ton of changes, then drop it again. However, if we have tests and CI, that'll already be doing a lot better than what we've got right now.

Breaking the project into folders doesn't really seem like a good option though. That's why I'd want a breaking version change. We just tag off the LKG of the current code, put a reference to that tag in the README, and go on with development. Forking or co-maintaining isn't really a good option here because we can barely keep one version of the project maintained as is.

**Comment by mdtdev** [comment]
Just a couple of comments from a part-time user (not developer): 

Re the comment by @warrenarea above about multiple headset use: We actually are (were?) planning on two headsets being fed into one program (from two users). It is further down the road, and more aspirational now than not, but it was an intent for our research program. Since Emotiv has killed their old developer API (that's our $2500 down the drain, thanks Emotiv!) this project is really the only way we could even imagine accessing raw EEG to proceed with that.

So breaking the multi-headset support is bad news; but not bad enough that I would beg for people to keep it. If it makes other things good, losing multiple headset support is probably the best choice for the project. As a user and not a developer/contributor I can see the need to drop it if it simplifies or improves the overall code. The main goal for this project should be providing a baseline of relatively ready access to the raw data. If that means the main goal is access to EEG for one headset, we'll take it!

Our usage model is currently mixed. When Emotiv rewrote the rules without warning we switched to using their _Testbench_ program for recording raw EEG and doing analysis offline. We would like to plan on using emokit as a library to eventually build both a new data recorder program (possibly integrating with [labstreaminglayer](https://github.com/sccn/labstreaminglayer) for real-time data movement) and also to use emokit as a library to build some real-time feedback displays (auditory and visual). We have been slow to work on these as we thought we had time and also thought we had a license for the manufacturers API. :disappointed: We are worried that at some point the installs of Emotiv's _Testbench_ program will fail and we will be without that, so we need a new data recorder that we can trust sooner rather than later. We were hoping to put some time in this upcoming fall to work on that.

I think that @qdot is right that this project needs to stay as unforked as possible, given the very limited base of interested parties. (A good example is me, who is worthless for development, but really needs these tools to be supported and continue improving/developing!) Transitioning to Python 3 is probably a good idea. I am sure it breaks someone's stuff, but if it keeps everyone focused on one codebase, that is probably a win in the long run. We have only played with emokit so far so that change is easier for us to live with.

As always, I/we are just thankful that you all have seen fit to work on this as getting to the raw data in the headset is a bit beyond where our skills are; though I think with that basis the other stuff we want to do is more plausible.

**Comment by warrenarea** [comment]
> We just tag off the LKG of the current code, put a reference to that tag in the README, and go on with development. Forking or co-maintaining isn't really a good option here because we can barely keep one version of the project maintained as is.

I think you said what needs to be done. I agree with your last statement, that we shouldn't try to
spread ourselves too thin, by co-maintaining multiple versions.

I think its settled, that development should be directed toward Py3 support.  I suspect most people want to move to Python 3 support, but just need a push toward it.

Perhaps we should explore some of the current projects that are currently using emokit.
a year ago I followed just about every emokit project available, so I've been receiving updates
on what projects are being utilized. I think the most activity i seen, apart from the regular
emokit issues, was probably from the hemokit project, which is similar to my cykit project,
which is capable of dumping the raw data to either a file, or to send via a TCP stream.

From what i've seen, some people are using it to connect to OpenVibe using the direct
raw telnet stream. Also, I think a lot of people may also be using it to try to connect it to
Matlab, which is also attractive because of its diverse modularized functions. 

I personally, have setup mine to connect with Unity3D, and use it to trigger some 
visualizations. 

One idea i had recently, is that what emokit might need, is something like a 
Toolkit, maybe to help analyze the signals received by emotiv.  

I think the real goal, which I might try to achieve in Unity3D is to create a
training system. To try and match the signal detection. 

gevent seems attractive, because it does have several features that have
potential... but ultimately, I think it adds a lot of moving parts to the equation,
that might not be necessary to the primary goal of emokit, which is receiving
raw data from the EEG headset. 

Perhaps we should be then offering links, of where people can go from here,
as whats the next step after receiving the raw data?

**Comment by qdot** [comment]
What would be nice is if we could modularize things a bit, and still provide a front end API similar to what we have now. I honestly have no idea if that's possible at the moment, mainly because I haven't looked at the code much in the past few years. I need to check out this patch and the current state of the code and see what we can do, and go from there.

Just gotta find time. :)

**Comment by warrenarea** [comment]
Not really related to the Py3 support topic, i but i also think Emotiv might be losing ground
also, to perhaps the Open BCI project... it offers more sensors, the headset is likely more stable
being in helmet form. Also, the plastic used is durable enough that it probably isn't going to
fall apart.  Plus, being open source, you're not being restricted with the licensing. 

I think the only thing going for emotiv right now, is its price tag, and the fact that not
everyone has a 3D printer.  Also their research done on their gel-based polymer contacts,
might give them an edge.  I think whats really holding Emotiv back though, is it has too
many strings attached, making it nearly impossible for someone to profit from anything
you create for it.

**Comment by mdtdev** [comment]
@warrenarea -- this is not a scientific sample at all, but more than half the people we know doing work with this level of equipment are moving off of Emotiv. 

That said, we have 5 freaking EPOC/EPOC+ headsets in our lab, and despite stories we've heard, none of them are falling apart despite fairly hard use in research. So while we're also branching out into OpenBCI, we expect to need EPOC/EPOC+ support for (hopefully) a couple of years to come.

But you hit the nail on the head: Emotiv seems to want to kill their usefulness for researchers. We cannot legally use their new PureEEG platform as it violates all of our human subject protection rules. They seem to want to leave academic/industrial research and focus on hobbyists who can comply with their subscription based raw data service. Not sure what their deal is!

**Comment by warrenarea** [comment]
I think gevent is too integrated to modularize in this manner, just got to make a decision.

I think another reason why gevent was used, is so that if you needed to do any additional
processing with python.... like in the case of pyRender, that it would receive the data while at the same 
time allowing you to do extra tasks like drawing to the screen. 

however, if people are just using emokit to dispatch the data to other programs,
and arn't doing any processing in Python at all, then this means that gevent 
wouldnt be necessary, and is probably just slowing up things.

**Comment by warrenarea** [comment]
Basically, what a good source from Emotiv Inc. told me is this.... they don't mind if we use
the raw data and emokit, as long as its educational, or for research, thats fine.
The moment you start making profit from it though.... that's when you cross the line with them.
So its not that they're trying to kill usefulness of research, but if you want to make 
anything commercial, basically every person who buys your product, which makes use of
raw data, would have to pay Emotiv, for use of that raw data.

**Comment by bschumacher** [comment]
I'm pretty sure that this change will impact performance significantly and not in a good way, also you removed my new export/import classes which could be used to dump the data #167.

The crypto parts seems good, but lets still try to have a multi-threaded/process approach. 

The decryption takes a toll on performance, so we wouldn't be capturing data from the headset in real time and possibly dropping/missing data on some platforms.

Gevent was introduced so I could run this on a Raspberry Pi. I think even on my macbook the python library was a little slow before gevent, but that was years ago so I could be wrong.

@warrenarea I hate the cheap plastic on this thing, lol.

Anyhow, I will try to make time this weekend to work on this and test your pull request.

**Comment by warrenarea** [comment]
> That said, we have 5 freaking EPOC/EPOC+ headsets in our lab, and despite stories we've heard, none of them are falling apart despite fairly hard use in research

I had a completely different story, when i took my first one apart... the soldered connections
literally just fell off the circuit board.

My second model i had, after a couple months i went to use it, and i handled it with kid
gloves... and the headset cracked and fell apart in a very short time.

Apparently what i was told, there was an issue in the factory, where the materials used
in the plastic, was in some sort of transition. Efforts were then made i think to resolve this
issue.  So its possible that you got lucky with the good batch of headsets. lol

**Comment by warrenarea** [comment]
I'll setup this pull request to work with my tcp stream, i should then be able to tell the performance differences, and will report back.

**Comment by warrenarea** [comment]
well, ive spent several hours working on this, and i came to the conclusion
that jonrei is trying to punish me for cutting Linux out of my cykit py3 port, by cutting
Windows out of this port. lol

I'll do commit so you can see my attempt at a linux+windows hybrid, but its
not functional yet, and still needs a bit of work yet.

**Comment by qdot** [comment]
Ok, so I wasn't starting this discussion with the plan on people hacking on this patch specifically, it's just where it happened. I'd really like to have some testing and stuff up to see what we're going to maintain/break before working farther.

**Comment by mdtdev** [comment]
@warrenarea 

> My second model i had, after a couple months i went to use it, and i handled it with kid
> gloves... and the headset cracked and fell apart in a very short time.
> 
> Apparently what i was told, there was an issue in the factory, where the materials used
> in the plastic, was in some sort of transition. Efforts were then made i think to resolve this
> issue. So its possible that you got lucky with the good batch of headsets. lol

Yikes! Maybe we did. That said, one of the headsets we bought in the middle now has a dead AF electrode so I'll likely be cutting into mine soon. I'll see if my experience matches yours.

> Basically, what a good source from Emotiv Inc. told me is this.... they don't mind if we use
> the raw data and emokit, as long as its educational, or for research, thats fine.
> The moment you start making profit from it though.... that's when you cross the line with them.

Well that is good news for me anyway as we only do research. So I am glad to hear that it is unlikely they'll send lawyers after this project. 

Still, like everyone else doing serious work in low-cost EEG we're aiming to move off of Emotiv's equipment at the first opportunity. It is a shame they did what they did.

**Comment by jonrei** [comment]
Ok, lots of good input here!
I agree that OpenBCI probably is the way of the future, but I guess everyone here is stuck with Emotiv for the time being...

My suggestion would be to keep the critical usb and decryption code in emokit.py as simple as possible.
This makes it easier to customize, easier to test and easier to debug.
Then create a set of scripts for the different use cases that we have:

- 	Serialize data to file [1]
- 	Visualize data in real-time [1]
- 	OpenVIBE support?
- 	Multi-headset support [2]
- 	Coroutines [3]
 

[1] For people using numpy and matplotlib, there exist [log.py](https://github.com/butternutdog/emoren/blob/master/log.py) and [plot.py](https://github.com/butternutdog/emoren/blob/master/log.py). I can include them in the PR if there is interest.

[2] By just parameterizing the usb device id that we read from, and maybe moving the device resolving out of emokit.py, it seems it would be rather easy to at least keep it simple to implement multi-headset support.

[3] If py3.5, why not asyncio (and await/async)?

**Comment by warrenarea** [comment]
I was thinking last night, whether there should be a Windows emokit.py version
and a Linux version. as the hidapi does seem to function a bit differently in the Linux version.

also... when I wrote my py3 version for Windows... my code looks drastically different
than this Linux commit.  I had tons of issues with the unicode conversions. 

particularly i had to encode mine to a latin-1 format, which was necessary to get it
in the right format.  I'm not sure how you found a way around that, unless the Linux
has a different setup. 

https://github.com/CymatiCorp/CyKit-Python-3.3/blob/master/emotiv.py

Thats a working windows version of emotiv.py for py3.3

**Comment by mdtdev** [comment]
@jonrei log.py and plot.py should be part of the master I think, that would be helpful for me, certainly, since I did not know they existed before you mentioned them.

@warrenarea A working windows version is **very** helpful for us; we are trapped in a windows based IT-infrastructure here! Hacking around to make Linux stuff work has been a real problem for us.

**Comment by warrenarea** [comment]
That py3.3 version posted in the link above should work for Windows.

**Comment by bschumacher** [comment]
Thanks for your contribution, may or may not have borrowed some of your code in my PR. Will definitely look into the Cryptography stuff next. Closing this for now.

**Pull request closed without merging**
